export component BufferLine {
    in-out property <physical-length> buffer;
    in-out property <physical-length> line-thickness;
    max-height: buffer;
    VerticalLayout {
        Rectangle {}        
        Rectangle {
            height: line-thickness;
            background: black;
        }
        Rectangle {}
    }
}

export component TableText inherits Rectangle{
    in-out property <string> text;
    Text { 
        text: text;
        horizontal-alignment: TextHorizontalAlignment.left;
        vertical-alignment: TextVerticalAlignment.center;
        overflow: TextOverflow.elide;
        wrap: TextWrap.no-wrap;
    }
}