import { Button, TabWidget, ListView, GridBox, LineEdit, StandardButton, ComboBox, ScrollView } from "std-widgets.slint";
import { Validation, IdType } from "validation.slint";
import { BufferLine, TableHeader, TableItem, TableItemActionIcons, TableText, CreationActionIcons } from "custom_widgets.slint";
import { LesseeData, LeaseholderInput, MessageType, WindowCallbacks, WindowType } from "globals.slint";
import { ColorPalette } from "palette.slint";

enum LesseeMenuState {totals, view}

export component AddLeaseholderMenu inherits Window {
    public function clear-lessee-menu() {
        name-input.text = "";
        street-input.text = "";
        city-input.text = "";
        state-input.text = "";
        zip-input.text = "";
        email-input.text = "";
        phone-input.text = "";
        move-in-input.text = "";
        lessee-action = MessageType.create;
    }

    public function open-lessee(lessee: LeaseholderInput) {
        name-input.text = lessee.name;
        street-input.text = lessee.street-address;
        city-input.text = lessee.city;
        state-input.text = lessee.state;
        zip-input.text = lessee.zip-code;
        email-input.text = lessee.email;
        phone-input.text = lessee.phone-number;
        move-in-input.text = lessee.move-in-date;

        LesseeData.selected-lessee-id = lessee.id;
        LesseeData.selected-lessee = lessee;
        lessee-action = MessageType.update;
    }

    public function submit-lessee() {
        LesseeData.new-lessee(
            lessee-action,
            {
            id: lessee-action == MessageType.update ? 
                            LesseeData.selected-lessee-id : 
                            lessee-action == MessageType.delete ? 
                            LesseeData.selected-lessee-id : 
                            LesseeData.potential-lessee-id,
            lease: lessee-action == MessageType.update ? 
                            LesseeData.selected-lessee.lease : 0,
            property-id: lessee-action == MessageType.update ? 
                            LesseeData.selected-lessee.property-id : 0,
            name: name-input.text,
            street_address: street-input.text,
            city: city-input.text,
            state: state-input.text,
            zip_code: zip-input.text,
            email: email-input.text,
            phone_number: phone-input.text,
            move_in_date: move-in-input.text,
        });

        clear-lessee-menu();
    }
    in-out property <MessageType> lessee-action;
    
    x: 20px; y: 20px; 
    min-height: 400px; min-width: 400px;
    preferred-height: 800px; preferred-width: 800px;
    Rectangle { 
        height:100%; 
        width: 100%; 
        background: ColorPalette.leaseholder-menu-bg;
        padding: 10px;HorizontalLayout {
            GridBox {
                width: 300px;
                spacing: 20px;
                padding: 10px;
                y: 10px;
                height: 50px;
                Text {
                    text: "Add Leaseholder";
                    col: 0;
                    row: 0;
                    font-weight: 3;
                }
                name-input := LineEdit {
                    col: 0;
                    row: 1;
                    //placeholder-text: "Leaseholder Name";
                    text: LesseeData.selected-lessee.name;
                    input-type: InputType.text;
                }
                street-input := LineEdit {
                    col: 0;
                    row: 2;
                    //placeholder-text: "Street Address";
                    text: LesseeData.selected-lessee.street-address;
                    input-type: InputType.text;
                }
                city-input := LineEdit {
                    col: 1;
                    row: 2;
                    //placeholder-text: "City";
                    text: LesseeData.selected-lessee.city;
                    input-type: InputType.text;
                }
                state-input := LineEdit {
                    col: 0;
                    row: 3;
                    //placeholder-text: "State";
                    text: LesseeData.selected-lessee.state;
                    input-type: InputType.text;
                }
                zip-input := LineEdit {
                    col: 1;
                    row: 3;
                    //placeholder-text: "Zip-Code";
                    text: LesseeData.selected-lessee.zip-code;
                    input-type: InputType.number;
                }
                email-input := LineEdit {
                    col: 0;
                    row: 4;
                    //placeholder-text: "Email";
                    text: LesseeData.selected-lessee.email;
                    input-type: InputType.text;
                }
                phone-input := LineEdit {
                    col: 1;
                    row: 4;
                    //placeholder-text: "Phone number";
                    text: LesseeData.selected-lessee.phone-number;
                    input-type: InputType.decimal;
                }
                move-in-input := LineEdit {
                    col: 0;
                    row: 5;
                    //placeholder-text: "Move-In Date";
                    text: LesseeData.selected-lessee.move-in-date;
                    input-type: InputType.text;
                }
                HorizontalLayout {
                    col: 0;
                    row: 6;
                    StandardButton {
                        kind: ok;
                        clicked => {
                            submit-lessee();
                            open-lessee(LesseeData.selected-lessee);
                        }
                    }
                    StandardButton {
                        kind: cancel;
                        clicked => {
                            clear-lessee-menu();
                        }
                    }
                    Button {
                        enabled: lessee-action == MessageType.update ? true : false;
                        text: "Delete";
                        clicked => {
                            lessee-action = MessageType.delete;
                            submit-lessee();
                        }
                    }
                }
            }
        }
    }
}

export component ViewLesseesMenu inherits Rectangle {
    in-out property <LeaseholderInput> selected-lessee;
    in-out property <string> lessee-subtype-string;
    in-out property <MessageType> lessee-action;
    y: 10px;
    x: 20px;
    padding: 10px;

    VerticalLayout {
        x: 30px;
        titles := HorizontalLayout {
            TableHeader { 
                width: 40px;
                text: "ID";
            }
            TableHeader { 
                width: 40px;
                text: "Lease ID";
            }
            TableHeader { 
                width: 100px;
                text: "Property ID";
            }
            TableHeader { 
                width: 150px;
                text: "Name";
            }
            TableHeader { 
                width: 70px;
                text: "Move-In Date";
            }
        }
        BufferLine { 
            buffer: 10px;
            line-thickness: 3px;
        }
        ScrollView {
            VerticalLayout {
                alignment: LayoutAlignment.start;
                preferred-width: 0in;
                x: 0cm;
                padding: 0;
                for x in LesseeData.lessees: lessee-line := HorizontalLayout {
                    lessee-id := TableItem {
                        width: 40px;
                        text: x.id;
                    }
                    lessee-lease-id := TableItem {
                        width: 40px;
                        text: x.lease;
                    }
                    lessee-prop-id := TableItem { 
                        width: 40px;
                        text: x.property-id;
                    }
                    lessee-name := TableItem { 
                        width: 150px;
                        text: x.name;
                    }
                    lessee-date := TableItem { 
                        width: 70px;
                        text: x.move-in-date;
                    }
                    lessee-action-icons := TableItemActionIcons {
                        width: 70px;
                        edit => {
                            LesseeData.selected-lessee = x;
                            WindowCallbacks.open-window(WindowType.Lessee);

                            /*
                            new-lessee-id.edit-text = x.id;
                            new-lessee-lease-id.edit-text = x.lease;
                            new-lessee-prop-id.edit-text = x.property-id;
                            new-lessee-name.edit-text = x.name;
                            new-lessee-date.edit-text = x.move-in-date;
                            */
                        }
                        delete => {
                            LesseeData.selected-lessee-id = x.id;
                            lessee-action = MessageType.delete;
                            selected-lessee = x;

                            LesseeData.new-lessee(
                                lessee-action,
                                {
                                id: LesseeData.selected-lessee-id,
                                name: x.name,
                                lease: x.lease,
                                property-id: x.property-id,
                                street-address: x.street-address,
                                city: x.city,
                                state: x.state,
                                zip_code: x.zip-code,
                                email: x.email,
                                phone-number: x.phone-number,
                                move-in-date: x.move-in-date
                            });
                        }
                    }
                }
            }
        }
        BufferLine { 
            buffer: 10px;
            line-thickness: 3px;
        }
        Rectangle {
            new-lessee := HorizontalLayout {
                out property <MessageType> current-use;
                new-lessee-id := TableText {                        
                    width: 40px;
                    default-text: "";
                }
                new-lessee-lease-id := TableText { 
                    width: 100px;
                    default-text: "Lease";
                }
                new-lessee-prop-id := TableText {
                    width: 40px;
                    default-text: "Property";
                }
                new-lessee-name := TableText { 
                    width: 150px;
                    default-text: "Name";
                }
                new-lessee-date := TableText { 
                    width: 70px;
                    default-text: "Date";
                }
                new-expense-action-icons := CreationActionIcons {
                    width: 70px;
                    confirm => {
                        
                        LesseeData.new-lessee(
                            new-lessee.current-use,
                            {
                            id: new-lessee.current-use == MessageType.update ?
                                selected-lessee.id :
                                Validation.get-valid-id(IdType.Leaseholder),
                            name: new-lessee-name.edit-text,
                            lease: new-lessee-lease-id.edit-text.to-float(),
                            property-id: new-lessee-prop-id.edit-text.to-float(),
                            street-address: "TEST",
                            city: "TEST",
                            state: "TEST",
                            zip_code: "TEST",
                            email: "TEST",
                            phone-number: "TEST",
                            move-in-date: new-lessee-date.edit-text
                        });
                    }
                    cancel => {
                        new-lessee.current-use = MessageType.create;

                        new-lessee-id.clear();
                        new-lessee-prop-id.clear();
                        new-lessee-name.clear();
                        new-lessee-lease-id.clear();
                        new-lessee-date.clear();
                    }
                }
            }
        }
        Rectangle {
            height: 10px;
        }
    }
}

export component LeaseholderMenu inherits Rectangle {
    HorizontalLayout {
        Rectangle {
            min-width: 400px;
            preferred-width: 600px;
            max-width: 1000px;
            property <LesseeMenuState> current-state: LesseeMenuState.totals;
            VerticalLayout {
                states [
                    View when current-state == LesseeMenuState.view : {
                        view-lessees-menu.visible : false;
                        main-view-menu.visible : true;
                    }
                    Totals when current-state == LesseeMenuState.totals : {
                        view-lessees-menu.visible : true;
                        main-view-menu.visible : false;
                    }
                ]
                HorizontalLayout {
                    Button {
                        text: "Leaseholders";
                        clicked => {
                            current-state = LesseeMenuState.totals;
                        }
                    }
                    Button {
                        text: "Visualizations";
                        clicked => {
                            current-state = LesseeMenuState.view;
                        }
                    }
                }
                Rectangle {
                    main-view-menu := Rectangle {
                        visible: false;
                    }
                    view-lessees-menu := ViewLesseesMenu {
                        visible: false;
                    }
                }                
            }
        }
    }
}