import { VerticalBox, HorizontalBox, ComboBox } from "std-widgets.slint";
import { TenantInfo, TenantData, ExpenseInfo, ExpenseData, PropertyInfo, PropertyData } from "globals.slint";

export { TenantInfo, TenantData, ExpenseInfo, ExpenseData, PropertyInfo, PropertyData }

export enum PageType { Home, Expenses, Tenants, Properties, Settings }

export component App inherits Window {
    function OpenContent(page: PageType) {
        home-info.visible = false;
        expense-info.visible = false;
        prop-info.visible = false;
        tenant-info.visible = false;
        settings-info.visible = false;
        
        change-page(page);
        current-page-type = page;

        if page == PageType.Home {
            current-page = "Home";
            home-info.visible = true;
        }
        if page == PageType.Expenses {
            current-page = "Expenses";
            expense-info.visible = true;
        }
        if page == PageType.Properties {
            current-page = "Properties";
            prop-info.visible = true;
        }
        if page == PageType.Tenants {
            current-page = "Tenants";    
            tenant-info.visible = true;
        }
        if page == PageType.Settings {
            current-page = "Settings";
            settings-info.visible = true;
        }
    }

    // === Window ===
    title: "Hestia";
    //always-on-top: true;
    //no-frame: true;

    // === Sizing ===
    min-width: 400px;
    preferred-width: 800px;
    min-height: 300px;
    preferred-height: 1000px;

    // === Elements ===
    padding: 10px;

    in-out property <string> current-page: "Home";
    in-out property <PageType> current-page-type: Home;

    callback change-page(PageType);
    
    HorizontalLayout {
        Rectangle {
            width: 60px;
            Rectangle {
                background: green;
                VerticalLayout {
                    alignment: LayoutAlignment.start;
                    padding: 10px;
                    spacing: 10px;
                    TouchArea {
                        Text {
                            text : "Home";
                        }
                        clicked => {
                            OpenContent(PageType.Home);
                        }
                    }
                    TouchArea {
                        Text {
                            text : "Expenses";
                        }
                        clicked => {
                            OpenContent(PageType.Expenses);
                        }
                    }
                    TouchArea {
                        Text {
                            text : "Properties";
                        }
                        clicked => {
                            OpenContent(PageType.Properties);
                        }
                    }
                    TouchArea {
                        Text {
                            text : "Tenants";
                        }
                        clicked => {
                            OpenContent(PageType.Tenants);
                        }
                    }
                    TouchArea {
                        Text {
                            text : "Settings";
                        }
                        clicked => {
                            OpenContent(PageType.Settings);
                        }
                    }
                }
            }
        }
        content-pane := Rectangle {             
            background: grey;
            
            Text {
                y: 20px;
                height: 40px;
                text: "Current Page is: " + current-page;
            }

            info-rect := Rectangle {
                home-info := Rectangle {
                    x: 10px;
                    y: 10px;
                    visible: true;
                    Text {
                        text: "Home Page Stuff";
                    }
                }
                expense-info := Rectangle {
                    x: 10px;
                    y: 10px;
                    visible: false;
                    Text {
                        text: @tr("You have {} expenses", ExpenseData.expenses.length);
                    }
                }
                prop-info := Rectangle {
                    x: 10px;
                    y: 10px;
                    visible: false;
                    Text {
                        text: @tr("You have {} properties", PropertyData.props.length);
                    }
                }
                tenant-info := Rectangle {
                    x: 10px;
                    y: 10px;
                    visible: false;
                    Text {
                        text: @tr("You have {} tenants", TenantData.tenants.length);
                    }
                }
                settings-info := Rectangle {
                    x: 10px;
                    y: 10px;
                    visible: false;
                    Text {
                        text: "No Settings Available at this time";
                    }
                } 
            }
        }
    }

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => { }
            }
        }
        Menu {
            title: @tr("Add");
            MenuItem {
                title: @tr("Property");
                activated => { }
            }
        }
        Menu {
            title: @tr("View");
        }
        Menu {
            title: @tr("Help");
        }
    }
}