export global ColorPalette {
    in property <color> button-default : #cfcd9cc5;
    in property <color> button-hovered : #45805d;
    in property <color> button-pressed : #ffa0a0;
    in property <color> button-border;
    in property <color> icon-bg;
    in property <color> window-bg : #ffedc4;

    in property <color> leaseholder-menu-bg : sienna.mix(gray, 20%);
    in property <color> expense-menu-bg : sienna.mix(gray, 20%);
    in property <color> prop-menu-bg : green.mix(gray, 20%);
    in property <color> statement-menu-bg : green.mix(gray, 20%);
}