import { Button, TabWidget, ListView } from "std-widgets.slint";

export struct PropertyInput {
    id: int,
    name: string,
    address-number: string,
    city: string,
    state: string,
    zip-code: string,
    property_tax: float,
    business_insurance: float,
    unit-count: int
}

export component PropertyMenu inherits Rectangle {
    in-out property <[PropertyInput]> properties;
    background: green.mix(gray, 20%);
    Rectangle {
        TabWidget {
            Tab {
                title: "Open Properties List";
                HorizontalLayout {
                    padding: 10px;
                    spacing: 10px;
                    alignment: start;
                    Rectangle {
                        min-width: 200px;
                        max-width: 400px;
                        border-radius: 2px;
                        border-color: black;
                        ListView {
                            padding: 20px;
                            for x in properties: expense-button := TouchArea {
                                Text {
                                    text: x.name;
                                }
                            }
                        }
                    }
                    Rectangle {
            
                    }
                }
            }
            Tab {
                title: "Add new Property";
                
            }
        }
    }
}