import { DatePickerPopup, Button, LineEdit, ScrollView, ComboBox } from "std-widgets.slint";
import { Date, MessageType, TransactionInfo, RegisterData } from "globals.slint";
import { TableHeader, BufferLine, TableItem, TableItemActionIcons, TableText, TableDate, CreationActionIcons } from "custom_widgets.slint";
import { IdType, Validation } from "validation.slint";

export component Register inherits Rectangle {
    in-out property <MessageType> message-type;
    //x: 20px;
    //padding: 10px;
    GridLayout {
        x: 5px;
        Row {
            HorizontalLayout {
                height: 30px;
                TableHeader {
                    width: 40px;
                    text: "ID";
                }
                TableHeader {
                    width: 40px;
                    text: "Property";
                }
                TableHeader {
                    width: 40px;
                    text: "Date";
                }
                TableHeader { 
                    width: 150px;
                    text: "Description";
                }
                TableHeader { 
                    width: 150px;
                    text: "Type";
                }
                TableHeader { 
                    width: 70px;
                    text: "Amount";
                }
            }
        }
        Row {
            BufferLine { 
                buffer: 10px;
                line-thickness: 2px;
            }
        }
        Row {
            ScrollView {
                VerticalLayout {
                    alignment: LayoutAlignment.start;
                    preferred-width: 0in;
                    x: 0cm;
                    padding: 0;
                    for x in RegisterData.transactions: transaction-line := HorizontalLayout {
                        transaction-id := TableItem {
                            width: 40px;
                            text: x.id;
                        }
                        transaction-prop-id := TableItem {
                            width: 40px;
                            text: x.prop-id;
                            //TODO: Translate prop id to property name. Maybe use combobox for the edit section
                            
                        }
                        transaction-date := TableItem { 
                            width: 100px;
                            text: @tr("{}/{}/{}", x.date.month, x.date.day, x.date.year);
                        }
                        transaction-description := TableItem { 
                            width: 150px;
                            text: x.description;
                        }
                        TableItem {
                            width: 150px;
                            text: x.transaction-type;
                        }
                        transaction-amount := TableItem { 
                            width: 70px;
                            text: x.amount;
                        }
                        transaction-action-icons := TableItemActionIcons {
                            width: 70px;
                            edit => {
                                RegisterData.selected-id = x.id;
                                message-type = MessageType.update;

                                id.edit-text = x.id;
                                prop-id.edit-text = x.prop-id;
                                description.edit-text = x.description;
                                date.set-date(x.date);
                                amount.edit-text = x.amount;
                                type.edit-text = x.transaction-type;
                            }
                            delete => {
                                RegisterData.selected-id = x.id;

                                RegisterData.new-transaction(
                                    MessageType.delete,
                                    {
                                        id: RegisterData.selected-id,
                                        description: x.description,
                                        amount: x.amount,
                                        date: x.date,
                                        transaction-type: x.transaction-type,
                                    },
                                );
                            }
                        }
                    }
                }
            }
        }
        Row {
            BufferLine { 
                buffer: 10px;
                line-thickness: 2px;
            }
        }
        Row {
            new-expense := HorizontalLayout {
                max-height: 20px;
                out property <MessageType> current-use;
                id := TableText {
                    width: 40px;
                    default-text: "";
                }
                prop-id := TableText {
                    width: 40px;
                    default-text: "Property";
                }
                date := TableDate {
                    width: 40px;
                    default-text: "Date";
                }
                description := TableText {
                    width: 150px;
                    default-text: "Description";
                }
                type := TableText {
                    width: 150px;
                    default-text: "Type";
                }
                amount := TableText {
                    width: 70px;
                    default-text: "Amount";
                }
                action-icons := CreationActionIcons {
                    width: 70px;
                    confirm => {
                        
                        RegisterData.new-transaction(
                            current-use,
                            {
                                id: current-use == MessageType.update ?
                                    RegisterData.selected-id :
                                    Validation.get-valid-id(IdType.Transaction),
                                prop-id: prop-id.edit-text.to-float(),
                                description: description.edit-text,
                                amount: amount.edit-text.to-float(),
                                date: date.current-date,
                                transaction-type: type.edit-text,
                            }
                        );
                    }
                    cancel => {
                        current-use = MessageType.create;

                        id.clear();
                        prop-id.clear();
                        description.clear();
                        amount.clear();
                        date.clear();
                        type.clear();
                    }
                }
            }
        }
        Row { }
    }
}

export component AddTransaction inherits Rectangle {
    width: 400px;
    height: 300px;

    in-out property <TransactionInfo> new-transaction;

    public function clear-menu() {
        prop_id.text = "";
        transaction_type.text = "";
        transaction_amount.text = "";
        month.text = "";
        day.text = "";
        year.text = "";
        transaction_description.text = "";
    }

    transaction-added := PopupWindow {
        Text {
            text: "Succesfully Added Transaction";
        }
    }

    VerticalLayout {
        spacing: 10px;
        padding: 20px;
        /*
        id: int,
        prop-id: int,
        expense-type: string,
        amount: float,
        date: string,
        description: string,
        */

        prop_id := LineEdit {
            placeholder-text: "Associated Property";
            input-type: number;
            width: 100%;
        }

        transaction_type := LineEdit {
            placeholder-text: "Type";
            width: 100%;
        }

        transaction_amount := LineEdit {
            placeholder-text: "Amount";
            input-type: number;
            width: 100%;
        }

        transaction_dates := Rectangle {
            in-out property <Date> date;
            popup := DatePickerPopup {
                accepted(date) => {
                    month.text = date.month;
                    day.text = date.day;
                    year.text = date.year;
                    popup.close();
                }
            }
            HorizontalLayout {
                width: parent.width;
                month := LineEdit {
                    placeholder-text: "Month";
                    input-type: InputType.number;
                    width: 30%;
                }
                day := LineEdit {
                    placeholder-text: "Day";
                    input-type: InputType.number;
                    width: 30%;
                }
                year := LineEdit {
                    placeholder-text: "Year";
                    input-type: InputType.number;
                    width: 30%;
                }
                picker := Button {
                    width: 10%;
                    clicked => {
                        popup.show();
                    }
                }
            }
        }

        transaction_description := LineEdit {
            placeholder-text: "Description";
            width: 100%;
        }

        HorizontalLayout {
            spacing: 10px;

            Button {
                text: "Add";
                clicked => {
                    RegisterData.new-transaction(
                        MessageType.create,
                        {
                            id: -1,
                            prop-id: -1,
                            transaction-type: transaction_type.text,
                            amount: transaction_amount.text.to-float(),
                            date: {
                                month: month.text.to-float(), 
                                day: day.text.to-float(), 
                                year: year.text.to-float(),
                            },
                            description: transaction_description.text
                        }
                    );

                    clear-menu();

                    transaction-added.show();
                }
            }

            Button {
                text: "Cancel";
                clicked => {
                    // Add logic to handle canceling the action
                    //console.log("Add Transaction Canceled");
                    clear-menu();
                }
            }
        }
    }
}
