import { ExpenseInput } from "globals.slint";

export enum IdType {
    Expense,
    Property,
    Leaseholder,
    Lease,
    Statement
}

export global Validation {
    pure callback get-valid-id(IdType) -> int;
    pure callback check-new-expense-validity(ExpenseInput) -> bool;    
    pure callback check-new-property-validity(ExpenseInput) -> bool;    
    pure callback check-new-lessee-validity(ExpenseInput) -> bool;
}