import { TransactionInfo, TenantInfo, PropertyInfo } from "globals.slint";

export enum IdType {
    Transaction,
    Property,
    Unit,
    Tenant,
    Lease,
    Statement
}

export global Validation {
    pure callback get-valid-id(IdType) -> int;
    pure callback check-new-transaction-validity(TransactionInfo) -> bool;    
    pure callback check-new-property-validity(PropertyInfo) -> bool;    
    pure callback check-new-tenant-validity(TenantInfo) -> bool;
}